options:
  auto-update: true
mobs:
- BLAZE
- CAVE_SPIDER
- CHICKEN
- COW
- CREEPER
- ENDERMAN
- ENDERMITE
- GHAST
- GUARDIAN
- HORSE
- IRON_GOLEM
- MAGMA_CUBE
- MUSHROOM_COW
- OCELOT
- PIG
- RABBIT
- SHEEP
- SILVERFISH
- SKELETON
- SLIME
- SPIDER
- SQUID
- VILLAGER
- WITHER_SKELETON
- WITCH
- WOLF
- ZOMBIE